#!/usr/bin/env bash

# abort on errors
set -e

# create git ignored working directory to push small delta update on publish
if [[ ! -d ./gitdist ]]; then
    git clone git@github.com:liorazio/liorazio.github.io.git gitdist
fi

# remove old deployment
find gitdist -maxdepth 1 ! -iname '.git' ! -iname 'gitdist' -print0 | xargs -0 -I{} rm -rf {}

# build
npm run build
version=$(node -p "require('./package.json').version")
# copy all build files to git working directory
cp -a ./dist/* ./gitdist/

cat <<'EOF' > ./gitdist/README.md
# Portfolio of Lior Raz

This [Vue.js](https://vuejs.org/guide/introduction.html) static router application is the [portfolio](https://github.com/liorazio/portfolio) of artist Lior Raz.

The application has 3 routes:
* [Home (/#/)](https://liorazio.github.io/#/)
* [About (/#/about)](https://liorazio.github.io/#/about)
* Gallery (/#/gallery/:id). with available gallery IDs:
  * [/#/gallery/gifs](https://liorazio.github.io/#/gallery/gifs)
  * [/#/gallery/illustrations](https://liorazio.github.io/#/gallery/illustrations)
  * [/#/gallery/sketch-book](https://liorazio.github.io/#/gallery/sketch-book)
  * [/#/gallery/dogo-dash](https://liorazio.github.io/#/gallery/dogo-dash)
  * [/#/gallery/golden-aggle](https://liorazio.github.io/#/gallery/golden-aggle)

All sources in this repository are auto-generated by [deploy.sh](https://github.com/liorazio/portfolio/blob/main/deploy.sh).

All images are copyrighted and are the property of Lior Raz, any use is strictly prohibited.

All code sources in the portfolio app are opensource under MIT license.

Fork me on GitHub!
EOF

# create and push deploy commit
pushd gitdist
git add .
#git commit -am "deploy version ${version} $(date '+%d-%b %H:%M')"
#git push origin HEAD
#popd
